# Generated by Django 6.1.1 on 2026-09-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone', models.PositiveIntegerField()),
                ('whatsapp_number', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
