# Generated by Django 6.1.1 on 2026-09-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teacher_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
