# Generated by Django 6.1.1 on 2026-09-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_teacher_is_active_teacher_joined_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
