# Generated by Django 6.1.1 on 2026-09-21 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grade', '0001_initial'),
        ('subject', '0004_remove_subject_default_monthly_fee'),
        ('teacher', '0006_teacher_salary_alter_teacher_whatsapp_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_fee', models.DecimalField(decimal_places=2, help_text='Default monthly fee for this class (e.g. 2500.00)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='grade.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='subject.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='teacher.teacher')),
            ],
            options={
                'verbose_name': 'Class / Batch',
                'verbose_name_plural': 'Classes / Batches',
            },
        ),
    ]
