# Generated by Django 6.1.1 on 2026-09-21 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('dob', models.DateField(default=datetime.datetime(2016, 9, 23, 5, 49, 57, 67274, tzinfo=datetime.timezone.utc))),
                ('parent_name', models.CharField(max_length=128)),
                ('parent_phone', models.CharField(max_length=12, unique=True)),
                ('whatsapp_number', models.CharField(max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
