# Generated by Django 6.1.1 on 2026-09-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
