# Generated by Django 6.1.1 on 2026-09-21 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batch', '0001_initial'),
        ('student', '0002_alter_student_dob_alter_student_parent_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('agreed_fees', models.DecimalField(blank=True, decimal_places=2, help_text='Custom fee for this student. If its Blank take the value of Subject fee from Batch Default Fee', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('class_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='batch.classbatch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='student.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'class_batch'), name='unique_student_class_enrollment')],
            },
        ),
    ]
