# Generated by Django 6.1.1 on 2026-09-19 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(default='TAM-6000', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 19, 4, 26, 10, 5814, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='subject',
            name='default_monthly_fee',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=7),
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 19, 4, 26, 10, 5857, tzinfo=datetime.timezone.utc)),
        ),
    ]
