# Generated by Django 6.1.1 on 2026-09-21 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_alter_subject_code_alter_subject_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='default_monthly_fee',
        ),
    ]
